version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 14 # Use a supported version (12 or 14)
    commands:
      - echo Installing npm dependencies...
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - echo Building Angular project started...
      - ng build --configuration=production # Remove the space around the '='

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  discard-paths: yes
